language: cpp

cache:
    directories:
        - /tmp/Rack
          #before_cache:
          #- rm -fr /tmp/Rack/plugins/sdr

matrix:
    include:
        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-7
          env:
              - MATRIX_EVAL="sudo apt install git curl cmake libx11-dev libglu1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev zlib1g-dev libasound2-dev libgtk2.0-dev libjack-jackd2-dev jq;CC=gcc-7 && CXX=g++-7"
        - os: osx
          osx_image: xcode10
          env:
              - MATRIX_EVAL="" #"brew install git wget cmake autoconf automake libtool"

before_install:
    - eval "${MATRIX_EVAL}"

before_script:
    - git clone --branch=v1 https://github.com/VCVRack/Rack.git /tmp/Rack || cd /tmp/Rack && git pull
    - cd /tmp/Rack
    - git submodule update --init --recursive
    - if [ $TRAVIS_OS_NAME == linux ]; then export ; fi
    - make dep -j4 #> /dev/null
    - make clean
    - make -j4
    - rm -rf /tmp/Rack/plugins/sdr || true
    - cp -r $TRAVIS_BUILD_DIR /tmp/Rack/plugins/sdr

script:
    - cd /tmp/Rack/plugins/sdr && make dist
