#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

namespace tfdsp::late_reverb_optimized_coefficients {

// Generated by tools/export_reverb_coefficients.py for the production
// Optimized flavour. The hand-authored Base coefficients remain in
// late_reverb_coefficients.hpp. Artifact SHA-256: 180a73743e00d0eaaf4d435ab5b87a7457e8150a4441114ebad6366e1b5bc55f
inline constexpr std::uint32_t DesignVersion = 1;
inline constexpr int SelectedStep = 44;
inline constexpr float SelectedLoss = 42.7085334f;
inline constexpr float OptimizationGridSeconds =
    32.0f;
inline constexpr std::size_t LineCount = 16;
inline constexpr std::size_t VelvetStageCount = 2;

inline constexpr std::array<float, LineCount> MainDelayRatio{
    0.56620367f, 0.629610988f, 0.679534129f, 0.730948331f, 0.788747351f, 0.851401051f, 0.92010052f, 0.967277707f, 1.02656655f, 1.07880874f, 1.13545105f, 1.20133857f, 1.26249072f, 1.32714254f, 1.38682775f, 1.44755034f};
inline constexpr std::array<std::array<float, LineCount>, VelvetStageCount>
    VelvetDelayMs{{
        {{0.125f, 0.875f, 1.375f, 2.0f, 2.75f, 3.25f, 3.875f, 4.5f, 5.25f, 5.75f, 6.375f, 7.125f, 7.75f, 8.25f, 9.125f, 9.75f}},
        {{0.375f, 1.0f, 1.625f, 2.375f, 2.875f, 3.625f, 4.125f, 4.875f, 5.375f, 6.125f, 6.75f, 7.375f, 8.0f, 8.75f, 9.375f, 10.125f}}
    }};
inline constexpr std::array<std::array<std::size_t, LineCount>,
                            VelvetStageCount + 1>
    TransformPermutation{{
        {{11, 1, 15, 0, 6, 3, 4, 13, 8, 10, 14, 12, 9, 7, 2, 5}},
        {{9, 10, 12, 4, 7, 5, 13, 1, 3, 6, 0, 8, 2, 15, 11, 14}},
        {{5, 12, 1, 9, 14, 3, 10, 0, 7, 15, 4, 11, 2, 13, 8, 6}}
    }};
inline constexpr std::array<std::array<float, LineCount>,
                            VelvetStageCount + 1>
    TransformSign{{
    {{-1.0f, -1.0f, -1.0f, -1.0f, -1.0f, -1.0f, 1.0f, -1.0f, -1.0f, -1.0f, 1.0f, -1.0f, -1.0f, -1.0f, 1.0f, -1.0f}},
    {{1.0f, -1.0f, -1.0f, 1.0f, -1.0f, 1.0f, -1.0f, 1.0f, 1.0f, 1.0f, 1.0f, -1.0f, -1.0f, 1.0f, 1.0f, -1.0f}},
    {{1.0f, -1.0f, 1.0f, 1.0f, -1.0f, -1.0f, 1.0f, -1.0f, 1.0f, -1.0f, -1.0f, 1.0f, -1.0f, 1.0f, 1.0f, -1.0f}}
}};

} // namespace tfdsp::late_reverb_optimized_coefficients
