#!/usr/bin/env python3
"""Export a fitted current-VFM artifact as a separate optimized flavour."""

from __future__ import annotations

import argparse
import hashlib
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ARTIFACT_FORMAT = "TriggerFish current two-stage VFM coefficients v1"
DEFAULT_ARTIFACT = ROOT / "data/reverb-calibration/velvet-vfm-current-v1.json"
DEFAULT_OUTPUT = ROOT / "src/tfdsp/late_reverb_optimized_coefficients.hpp"
LINE_COUNT = 16
VELVET_STAGE_COUNT = 2


def float_literal(value: float) -> str:
    if not math.isfinite(value):
        raise ValueError("coefficient values must be finite")
    encoded = f"{value:.9g}"
    if "." not in encoded and "e" not in encoded.lower():
        encoded += ".0"
    return encoded + "f"


def floats(values: list[float]) -> str:
    return ", ".join(float_literal(value) for value in values)


def integers(values: list[int]) -> str:
    return ", ".join(str(value) for value in values)


def validate_artifact(artifact: dict) -> None:
    if artifact.get("format") != ARTIFACT_FORMAT:
        raise ValueError("artifact is not a current two-stage VFM fit")
    architecture = artifact.get("architecture", {})
    if (
        architecture.get("line_count") != LINE_COUNT
        or architecture.get("velvet_stage_count") != VELVET_STAGE_COUNT
    ):
        raise ValueError("artifact architecture does not match production")
    main_ratios = artifact.get("main_delay_ratio", [])
    velvet_delays = artifact.get("velvet_delay_ms", [])
    permutations = artifact.get("permutations", [])
    signs = artifact.get("signs", [])
    if not (
        len(main_ratios) == LINE_COUNT
        and all(math.isfinite(value) and value > 0.0 for value in main_ratios)
        and all(
            main_ratios[index] < main_ratios[index + 1]
            for index in range(LINE_COUNT - 1)
        )
        and abs(sum(main_ratios) / LINE_COUNT - 1.0) < 1.0e-5
        and len(velvet_delays) == VELVET_STAGE_COUNT
        and all(
            len(stage) == LINE_COUNT
            and all(math.isfinite(value) and value > 0.0 for value in stage)
            for stage in velvet_delays
        )
        and len(permutations) == VELVET_STAGE_COUNT + 1
        and all(sorted(row) == list(range(LINE_COUNT)) for row in permutations)
        and len(signs) == VELVET_STAGE_COUNT + 1
        and all(len(row) == LINE_COUNT and set(row) <= {-1.0, 1.0} for row in signs)
    ):
        raise ValueError("artifact coefficients have invalid dimensions or constraints")


def render_header(artifact: dict, digest: str) -> str:
    main_ratios = artifact["main_delay_ratio"]
    velvet_delays = artifact["velvet_delay_ms"]
    permutations = artifact["permutations"]
    signs = artifact["signs"]
    delay_rows = ",\n        ".join("{{" + floats(row) + "}}" for row in velvet_delays)
    permutation_rows = ",\n        ".join(
        "{{" + integers(row) + "}}" for row in permutations
    )
    sign_rows = ",\n    ".join("{{" + floats(row) + "}}" for row in signs)
    selected_loss = artifact.get("best_loss")
    if selected_loss is None:
        history = artifact.get("history") or [{"total": 0.0}]
        selected_loss = history[-1]["total"]
    return f"""#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

namespace tfdsp::late_reverb_optimized_coefficients {{

// Generated by tools/export_reverb_coefficients.py for the optional Optimized
// flavour. The hand-authored Base coefficients remain in
// late_reverb_coefficients.hpp. Artifact SHA-256: {digest}
inline constexpr std::uint32_t DesignVersion = 1;
inline constexpr int SelectedStep = {artifact.get("best_step", 0)};
inline constexpr float SelectedLoss = {float_literal(selected_loss)};
inline constexpr float OptimizationGridSeconds =
    {float_literal(artifact["frequency_seconds"])};
inline constexpr std::size_t LineCount = {LINE_COUNT};
inline constexpr std::size_t VelvetStageCount = {VELVET_STAGE_COUNT};

inline constexpr std::array<float, LineCount> MainDelayRatio{{
    {floats(main_ratios)}}};
inline constexpr std::array<std::array<float, LineCount>, VelvetStageCount>
    VelvetDelayMs{{{{
        {delay_rows}
    }}}};
inline constexpr std::array<std::array<std::size_t, LineCount>,
                            VelvetStageCount + 1>
    TransformPermutation{{{{
        {permutation_rows}
    }}}};
inline constexpr std::array<std::array<float, LineCount>,
                            VelvetStageCount + 1>
    TransformSign{{{{
    {sign_rows}
}}}};

}} // namespace tfdsp::late_reverb_optimized_coefficients
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("artifact", nargs="?", type=Path, default=DEFAULT_ARTIFACT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    encoded = args.artifact.read_bytes()
    artifact = json.loads(encoded)
    validate_artifact(artifact)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        render_header(artifact, hashlib.sha256(encoded).hexdigest()),
        encoding="utf-8",
    )
    print(args.output)


if __name__ == "__main__":
    main()
